search_task:
  description: >
    Collect information on potential travel destinations based on user inputs, such as 
    budget, interests, location, and filters. Example filters include:
      - Geographical region (e.g., Europe, Southeast Asia).
      - Travel duration (e.g., weekend trips, two-week vacations).
      - Climate preferences (e.g., beach destinations, cold weather).
      - Special interests (e.g., family-friendly, historical landmarks, adventurous activities).
  expected_output: >
    A comprehensive report in JSON format detailing potential vacation destinations and 
    associated travel details (e.g., attractions, accommodations, transportation).
  inputs:
    - user_preferences
    - destination_filter
  output_format: JSON
  agent: research_specialist

recommendation_task:
  description: >
    Analyze user preferences and travel options to generate personalized recommendations.
    Consider factors such as budget, interests, travel dates, and preferred destinations.
  expected_output: >
    A structured JSON object containing the top 3 recommendations, each with a title, description, 
    and any associated costs or details.
  inputs:
    - user_preferences
    - travel_options
  output_format: JSON
  agent: recommendation_specialist

